In [1]:
import numpy

In [21]:
vector = numpy.array([5,10,15,4])
matrix = numpy.array([[5,10,15],[20,25,30],[35,40,45]])
print(vector)
print(matrix)

[ 5 10 15  4]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [5]:
print(vector.shape)

(4,)


In [6]:
print(matrix.shape)

(3, 3)


In [7]:
print(vector.dtype)

int64


In [12]:
print(vector.dtype)

<U21


In [13]:
print(vector[0:3])

['5' '10' '15']


In [16]:
print(matrix[:,0:2])

[[ 5 10]
 [20 25]
 [35 40]]


In [22]:

vector == 10

array([False,  True, False, False])

In [23]:
matrix == 25

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [24]:
matrix[:,1] == 25

array([False,  True, False])

In [26]:
matrix[1,] == 25

array([False,  True, False])

In [28]:
(vector == 10) & (vector == 5)

array([False, False, False, False])

In [29]:
(vector == 10) | (vector == 5)

array([ True,  True, False, False])

In [30]:
vector = vector.astype(float)
print(vector)

[ 5. 10. 15.  4.]


In [33]:
print(vector.max())

15.0


In [34]:
print(vector.sum())

34.0


In [35]:
print(matrix.sum(axis=1))

[ 30  75 120]


In [36]:
print(matrix.sum(axis=0))

[60 75 90]


In [39]:
import numpy as np
print(np.arange(15).reshape(3,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [40]:
a = np.arange(15).reshape(3,5)
print(a.shape)

(3, 5)


In [41]:
print(a.ndim)

2


In [42]:
print(a.dtype.name)

int64


In [43]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
np.ones((2,3,4),dtype=np.int32)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [49]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [52]:
np.random.random((2,3))

array([[0.3334325 , 0.40098477, 0.9551264 ],
       [0.62706479, 0.03883297, 0.29233915]])

In [56]:
from numpy import pi
np.linspace(0,2*pi,100)

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [57]:
a = np.array([20,30,40,50])
b = np.arange(4)
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [58]:
c = a-b
print(c)

[20 29 38 47]


In [59]:
print(b**2)

[0 1 4 9]


In [60]:
print(a<35)

[ True  True False False]


In [62]:
a = np.array([[1,1],[0,1]])
b = np.array([[2,0],[3,4]])
print(a)
print(b)

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]


In [63]:
print(a*b)

[[2 0]
 [0 4]]


In [64]:
print(a.dot(b))

[[5 4]
 [3 4]]


In [65]:
print(np.dot(a,b))

[[5 4]
 [3 4]]


In [66]:
b = np.arange(3)
print(np.exp(b))

[1.         2.71828183 7.3890561 ]


In [67]:
print(np.sqrt(b))

[0.         1.         1.41421356]


In [68]:
a = np.floor(10*np.random.random((3,4)))
print(a)

[[4. 4. 7. 1.]
 [8. 6. 7. 1.]
 [0. 6. 2. 1.]]


In [70]:
print(a.ravel())

[4. 4. 7. 1. 8. 6. 7. 1. 0. 6. 2. 1.]


In [72]:
a.shape = (6,2)
print(a)

[[4. 4.]
 [7. 1.]
 [8. 6.]
 [7. 1.]
 [0. 6.]
 [2. 1.]]


In [76]:
print(a.reshape(3,-1))

[[4. 4. 7. 1.]
 [8. 6. 7. 1.]
 [0. 6. 2. 1.]]


In [77]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
print(np.hstack((a,b)))

[[0. 0. 9. 4.]
 [8. 0. 8. 0.]]


In [78]:
a = np.floor(10*np.random.random((2,12)))
print(a)


[[6. 1. 9. 5. 0. 1. 8. 5. 9. 6. 3. 3.]
 [7. 8. 0. 7. 8. 8. 7. 2. 6. 5. 5. 0.]]


In [79]:
print(np.hsplit(a,3))

[array([[6., 1., 9., 5.],
       [7., 8., 0., 7.]]), array([[0., 1., 8., 5.],
       [8., 8., 7., 2.]]), array([[9., 6., 3., 3.],
       [6., 5., 5., 0.]])]


In [80]:
print(np.hsplit(a,(3,4)))

[array([[6., 1., 9.],
       [7., 8., 0.]]), array([[5.],
       [7.]]), array([[0., 1., 8., 5., 9., 6., 3., 3.],
       [8., 8., 7., 2., 6., 5., 5., 0.]])]


In [82]:
a = np.floor(10*np.random.random((12,2)))
print(np.vsplit(a,3))

[array([[1., 2.],
       [8., 9.],
       [6., 6.],
       [2., 4.]]), array([[4., 2.],
       [2., 1.],
       [0., 2.],
       [7., 7.]]), array([[7., 3.],
       [8., 2.],
       [9., 3.],
       [8., 6.]])]
